version: '3'

env:
  ENV: local

dotenv: ['.env', '.env.{{.ENV}}']

tasks:

  default:
    cmds:
      - task --list-all

  docker:
    cmds:
      - docker run -it --rm 
        -p 8080:8080
        -v $(pwd):/app
        sandbox-rust bash
